/*
 * Copyright (c) 2006-2026, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SVM_CONFIG_H
#define SVM_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define SVM_CONTROL_PERIOD_S           (1.0e-4f)
#define SVM_TWO_PI                     (6.2831853071795864769f)
#define SVM_PI                         (3.1415926535897932385f)
#define SVM_HALF_PI                    (1.5707963267948966192f)
#define SVM_SQRT3                      (1.7320508075688772935f)
#define SVM_INV_SQRT3                  (0.5773502691896257645f)
#define SVM_SQRT3_OVER_2               (0.8660254037844386468f)

#define SVM_DEFAULT_OUTER_VOLTAGE_KP   (0.2f)
#define SVM_DEFAULT_OUTER_VOLTAGE_KI   (210.0f)
#define SVM_DEFAULT_INNER_CURRENT_KP   (5.0f)
#define SVM_DEFAULT_INNER_CURRENT_KI   (220.0f)
#define SVM_DEFAULT_VOLTAGE_CROSS_GAIN (50.0f * SVM_PI * 15.0e-6f)
#define SVM_DEFAULT_CURRENT_CROSS_GAIN (50.0f * SVM_PI * 1.0e-2f)

#define SVM_DEFAULT_UD_REF             (12.0f)
#define SVM_DEFAULT_UQ_REF             (0.0f)

#define SVM_DEFAULT_DC_HV_VOLTAGE      (32.0f)
#define SVM_DEFAULT_DC_LV_VOLTAGE      (16.0f)
#define SVM_DEFAULT_OUTPUT_VOLTAGE_MAG (12.0f)
#define SVM_POWER_SPLIT_XI_MIN(v_h, v_l, v_mag) \
    (1.0f - (((v_h) - (v_l)) / (SVM_SQRT3 * (v_mag))))
#define SVM_POWER_SPLIT_XI_MAX(v_l, v_mag) \
    ((v_l) / (SVM_SQRT3 * (v_mag)))
#define SVM_CLAMP_UNIT_CONST(x) \
    (((x) > 1.0f) ? 1.0f : (((x) < 0.0f) ? 0.0f : (x)))
#define SVM_DEFAULT_POWER_SPLIT_XI_MIN \
    SVM_POWER_SPLIT_XI_MIN(SVM_DEFAULT_DC_HV_VOLTAGE, \
                           SVM_DEFAULT_DC_LV_VOLTAGE, \
                           SVM_DEFAULT_OUTPUT_VOLTAGE_MAG)
#define SVM_DEFAULT_POWER_SPLIT_XI_MAX \
    SVM_POWER_SPLIT_XI_MAX(SVM_DEFAULT_DC_LV_VOLTAGE, \
                           SVM_DEFAULT_OUTPUT_VOLTAGE_MAG)
#define SVM_DEFAULT_POWER_SPLIT_R \
    (SVM_DEFAULT_DC_LV_VOLTAGE / SVM_DEFAULT_DC_HV_VOLTAGE)
#define SVM_DEFAULT_POWER_SPLIT_XI_LOWER \
    SVM_CLAMP_UNIT_CONST(SVM_DEFAULT_POWER_SPLIT_XI_MIN)
#define SVM_DEFAULT_POWER_SPLIT_XI_UPPER \
    SVM_CLAMP_UNIT_CONST(SVM_DEFAULT_POWER_SPLIT_XI_MAX)
#define SVM_DEFAULT_POWER_SPLIT_XI_CLAMP_LOWER \
    ((SVM_DEFAULT_POWER_SPLIT_XI_LOWER > SVM_DEFAULT_POWER_SPLIT_XI_UPPER) ? \
     SVM_DEFAULT_POWER_SPLIT_XI_UPPER : SVM_DEFAULT_POWER_SPLIT_XI_LOWER)
#define SVM_DEFAULT_POWER_SPLIT_XI_CLAMP_UPPER \
    SVM_DEFAULT_POWER_SPLIT_XI_UPPER
#define SVM_CLAMP_DEFAULT_POWER_FACTOR_CONST(x) \
    (((x) > SVM_DEFAULT_POWER_SPLIT_XI_CLAMP_UPPER) ? \
     SVM_DEFAULT_POWER_SPLIT_XI_CLAMP_UPPER : \
     (((x) < SVM_DEFAULT_POWER_SPLIT_XI_CLAMP_LOWER) ? \
      SVM_DEFAULT_POWER_SPLIT_XI_CLAMP_LOWER : (x)))
#define SVM_DEFAULT_POWER_FACTOR \
    SVM_DEFAULT_POWER_SPLIT_R

#define SVM_MIN_DC_VOLTAGE             (0.0f)
#define SVM_DEFAULT_FREQ_HZ            (50.0f)

#ifdef __cplusplus
}
#endif

#endif /* SVM_CONFIG_H */
