from building import *
import os

cwd = GetCurrentDir()

src = []
CPPPATH = []
for root, dirs, files in os.walk(cwd):
    if 'build' in dirs:
        dirs.remove('build')
    c_files = [os.path.join(root, item) for item in files if item.endswith('.c')]
    if c_files:
        src += c_files
    if any(item.endswith(('.h', '.c')) for item in files):
        CPPPATH.append(root)

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
